### ISSUE TITLE
Why can't the number of images align with GT and the file names don't seem to correspond one-to-one either

### ISSUE THREAD

**Issue by lyq-y** [ntu-aris/MMAUD#1]
Hello dear author, thank you very much for your open source work, I have encountered some problems working with your dataset, including:
First of all, if it is based on a` 2D object detection task`, what does the` 3D vector in GT` mean?
On the other hand, the number of GTs and file names don't seem to correspond one-to-one with images.
best wishes to you!

**Comment by snakehaihai** [comment]
Hi 

The 3D vector in the GT denotes the tracked pose of the UAV with respect to the Leica Frame. Leica is one of the most accurate tools for outdoor precision trajectory estimation. This measurement uncertainty should be less than 1 cm. 

It is common as each camera is running 30hz. LIDARs are 10hz and ground truth is only 10hz.  Usually you don't need to worry about the stamp differences as the result trajectory you predicted can be used to compare with the ground truth trajectory using EVO https://github.com/MichaelGrupp/evo 

I`ll upload an other set of evaluation pipeline script in next month.  

![image](https://github.com/ntu-aris/MMAUD/assets/6070995/2be0d6fa-396e-4d56-a4cc-f55212576f56)


Rgs

Shenghai Yuan
