### ISSUE TITLE
About audio files

### ISSUE THREAD

**Issue by ach1llea** [ntu-aris/MMAUD#10]
Hello, how can I obtain the raw audio files? They don't seem to be included in the zip file. Thanks.

**Comment by snakehaihai** [comment]
Hi Gokaii

For v1. you may refer to https://github.com/yizhuoyang/AV-PedAware/tree/main  to extract audio from rosbag.

For v2 and v3, some of the audio is not available as it is too far away from the capture device, and the ambient noise is too noisy.
