### ISSUE TITLE
Work like art for the community open source

### ISSUE THREAD

**Issue by softwarePupil** [ntu-aris/MMAUD#3]
Your work is a pleasure to read, and as you say in your article, most of the units in the field refuse to open source their work, so may I ask, what is the approximate time to open source the multimodal data for other UAV models?

**Comment by snakehaihai** [comment]
MMAUD V1 (collected at rooftop with total raw data of 250G, after compression is < 80G) is already open.  <- this is what i promised in ICRA paper. will upload all before ICRA 2024 start. 

V2 (Collect at carpark for CVPR challenge trial, roughly 800G) is compressing
V3 (Collect at carpark for CVPR challenge Final, roughly 500G) is pending for compressing

For V1 you may try to download
