### ISSUE TITLE
Unable to download data set

### ISSUE THREAD

**Issue by mcarvalho2001** [ntu-aris/MMAUD#4]
Hey! I tried to download the .zip files from the data set and couldn't do it because it redirects me to the initial page of the repo. Also, when I try to download any ROSBag data file, it says that I don't have permission. Could you fix it or share those files with me? I was trying to understand if they will be useful for my thesis - it would eventually serve as a data set to predict fast-moving UAV trajectories. Thank you!

**Comment by snakehaihai** [comment]
Im currently still at yokohama. Will go back on monday to fix the access right issue. Thanks

**Comment by snakehaihai** [comment]
@mcarvalho2001 I`ve change the access to public. Do let me know if you have other problems.

Rgs
Shenghai Yuan
