### ISSUE TITLE
.zip not downloading

### ISSUE THREAD

**Issue by efectual** [ntu-aris/MMAUD#5]
**Describe the BUG**
.bag's available but .zips not available
**To Reproduce**
macos safari
https://ntu-aris.github.io/MMAUD/
click .zip
nothing

**Site link or Repository**

**Comment by snakehaihai** [comment]
ok uploading

**Comment by snakehaihai** [comment]
All Zip should be ready to download if you can not download it. do let me know

**Comment by molchanov-vs** [comment]
<img width="962" alt="Screenshot 2024-09-07 at 11 30 49" src="https://github.com/user-attachments/assets/bd26b37e-59fe-411d-89d4-e362fbc74dbc">
All .zip links don't work. Please check them

**Comment by snakehaihai** [comment]
@molchanov-vs

Hi. For V2 and V3, it is not in the ICRA paper contribution but is a separate CVPR challenge.

You may look at this google drive to download the section.  https://drive.google.com/drive/folders/1wk-c5xVX6701WNI_In1ba3_D4LSjRYv5


Rgs

Shenghai Yuan

**Comment by Nasakenaii** [comment]
Hello, 
The google drive link doesn't work anymore for the hard and moderate, could you please provide another link ? 

Thank you.

**Comment by snakehaihai** [comment]
> Hello, The google drive link doesn't work anymore for the hard and moderate, could you please provide another link ?
> 
> Thank you.

Hi. I just tested this URL and it still works. Could it be that you are in China and didn't use VPN?
