### ISSUE TITLE
There is no audio datasets in the published version

### ISSUE THREAD

**Issue by liyihao17** [ntu-aris/MMAUD#6]
**Describe the BUG**
I saw that the introduction of this project in "https://ntu-aris.github.io/MMAUD/", there is four audio array nodes in dataset. However, after downloading the published datasets, there is no audio file.

**Comment by snakehaihai** [comment]
Audio is in the bag. you need to follow the URL below  

https://docs.google.com/document/d/12u2E4NLQzOtWxfTxPNV5JmIW54Tqq5v7CQbI7BGwuQw/edit

to extract them.

Different durations of the audio clips affect the system's performance. We can't allocate all configurations.

You may follow the rest of the code here to have minimal reproduction samples.  

https://github.com/yizhuoyang/AV-PedAware/tree/main

Rgs
SHenghai Yuan
