### ISSUE TITLE
鱼眼相机的图片有2d的label吗

### ISSUE THREAD

**Issue by yyq19990828** [ntu-aris/MMAUD#7]

**Comment by snakehaihai** [comment]
没有 这个可以用labelme 手标几个。 或者直接用轨迹生成ROI 对相机覆盖

**Comment by yyq19990828** [comment]
这是来自QQ邮箱的自动回复邮件。已经成功收到你的邮件

**Comment by snakehaihai** [comment]
.....老6真牛  QQ 自动回复github

**Comment by yyq19990828** [comment]
大佬可以说详细一点吗，我不是做雷达相机融合这一块的 TOT

> 没有 这个可以用labelme 手标几个。 或者直接用轨迹生成ROI 对相机覆盖

**Comment by snakehaihai** [comment]
参考这个 https://www.v7labs.com/blog/labelme-guide

下载文件夹的数据 然后用这个里面的处理
